Repository ms-club-sliit/minihackathon-2024, pull requests merged in 2024-07, with the labels that each got.

#15 Feat/eligibility
  app/_components/Home/Eligibility/index.jsx
Labels: subtask

#14 Countdown Timer Implemented
  app/_components/Home/CountdownTimer/index.jsx
  app/_components/Home/CountdownTimer/timer.jsx
  app/globals.css
  app/page.jsx
  public/ctbg.png
Labels: enhancement, feature

#12 Feature/header - Implement header according to UI specifications
  components/Header/index.jsx
  package-lock.json
  package.json
  public/images/icons/menu.png
  public/images/logos/Facebook.png
  public/images/logos/GitHub.png
  public/images/logos/Instagram.png
  public/images/logos/Twitter.png
  public/images/logos/logomain.png
Labels: feature

#16 Feature/footer Implementation
  components/Footer/index.jsx
  package-lock.json
  package.json
  public/images/logos/FCSCLogo.png
  public/images/logos/MLSALogo.png
  public/images/logos/MSLogo.png
Labels: enhancement

#23 Styles updated & Minor Fixes
  app/_components/Home/CountdownTimer/index.jsx
  app/data/home/sponsors.json
  app/globals.css
  package-lock.json
  package.json
  public/images/ctbg.png
Labels: bug

#22 Feat/timeline
  app/_components/Home/Timeline/index.jsx
  app/data/Timeline.json
  app/globals.css
  package-lock.json
  package.json
  public/images/design-left.png
  public/images/design-right.png
  public/images/robot-end.png
  public/images/robot-right.png
  public/images/robot-top-old.png
  public/images/robot-top.png
Labels: subtask

#25 Fix/timer hydration
  app/_components/Home/CountdownTimer/timer.jsx
Labels: bug

#27 Feature/rules page
  app/_components/Rules/Content/index.jsx
  app/_components/Rules/Title/index.jsx
  app/data/rules/rules.json
  app/globals.css
  app/rules/page.jsx
  package-lock.json
Labels: feature

#28 Feat : Hero section done
  .eslintrc.json
  app/_components/Home/Hero/index.jsx
  package-lock.json
  public/images/AIBot.png
  tailwind.config.js
Labels: subtask

#38 pastwinner section update
  .github/workflows/azure-static-web-apps-lively-hill-005a24b10.yml
  app/_components/Home/PastWinners/index.jsx
  app/data/home/PastWinners.json
  app/page.jsx
  components/Home/PastWinner/index.jsx
  public/images/home/pastWinners/winner.png
Labels: enhancement
